# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-26 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='tip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
