# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-29 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20191129_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
