# Generated by Django 2.2.7 on 2019-12-16 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0004_auto_20191129_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'variant', 'verbose_name_plural': 'variants'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tip',
        ),
        migrations.RemoveField(
            model_name='test',
            name='task',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='task',
        ),
        migrations.AddField(
            model_name='tag',
            name='task',
            field=models.ManyToManyField(related_name='tasks', to='tests.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tests.Variant'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='profile',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='tests.Profile'),
            preserve_default=False,
        ),
    ]
