# Generated by Django 2.2.7 on 2019-12-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(default='12345678', max_length=30),
        ),
    ]
