# Generated by Django 2.2.7 on 2019-12-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_remove_profile_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='number_of_variant',
            new_name='number_of_variants',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='task',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='test',
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(related_name='tasks', to='tests.Tag'),
        ),
        migrations.AddField(
            model_name='test',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.Variant'),
        ),
        migrations.AlterField(
            model_name='test',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.Profile'),
        ),
    ]
