# Generated by Django 2.2.7 on 2019-12-27 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_auto_20191217_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='variant',
        ),
        migrations.AddField(
            model_name='variant',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tests.Test'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='profile',
        ),
        migrations.AddField(
            model_name='task',
            name='profile',
            field=models.ManyToManyField(default=1, related_name='tasks', to='tests.Profile'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='variant',
        ),
        migrations.AddField(
            model_name='task',
            name='variant',
            field=models.ManyToManyField(null=True, related_name='tasks', to='tests.Variant'),
        ),
    ]
