# Generated by Django 2.2.7 on 2020-01-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20191227_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='variant',
            field=models.ManyToManyField(related_name='tasks', to='tests.Variant'),
        ),
    ]
