# Generated by Django 2.2.7 on 2020-01-19 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_auto_20200119_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='test',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
