# Generated by Django 2.2.7 on 2020-01-19 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tests.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0014_auto_20200119_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='test',
            name='profile',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ManyToManyField(default=1, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='user',
            field=models.ForeignKey(default=tests.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
