# Generated by Django 2.2.7 on 2020-01-20 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_auto_20200120_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='tests.Test'),
        ),
    ]
