# Generated by Django 2.2.7 on 2020-01-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_auto_20200121_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='variant',
        ),
        migrations.AddField(
            model_name='task',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tests.Variant'),
        ),
    ]
