# Generated by Django 3.0.4 on 2020-03-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_auto_20200121_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='number_of_variant',
        ),
        migrations.AddField(
            model_name='test',
            name='number_of_variant',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
