# Generated by Django 3.0.4 on 2020-03-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_auto_20200317_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='number_of_variant',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
