# Generated by Django 3.0.4 on 2020-04-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_variant_number_of_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='number_of_variant',
        ),
        migrations.AddField(
            model_name='test',
            name='count_of_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='count_of_variants',
            field=models.IntegerField(default=0),
        ),
    ]
