# Generated by Django 3.0.4 on 2020-04-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0022_auto_20200424_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.CharField(default='Алгебра', max_length=50),
        ),
    ]
