# Generated by Django 3.0.4 on 2020-05-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0024_auto_20200505_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='category',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='Арифметика', max_length=50),
        ),
    ]
