# Generated by Django 3.0.4 on 2020-05-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0025_auto_20200506_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='test',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
