# Generated by Django 3.0.4 on 2020-06-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0029_auto_20200620_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='count_of_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
